//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DocumentLibraryManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Document
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Document()
        {
            this.Document_File = new HashSet<Document_File>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int Category_Id { get; set; }
        public int Sub_Category_Id { get; set; }
        public int Document_Source_Id { get; set; }
        public int Fiscal_Year_Id { get; set; }
        public int State_Id { get; set; }
        public int District_Id { get; set; }
        public int Palika_Id { get; set; }
        public int Document_Type_Id { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual District District { get; set; }
        public virtual Document_Source Document_Source { get; set; }
        public virtual Document_Type Document_Type { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Document_File> Document_File { get; set; }
        public virtual Fiscal_Year Fiscal_Year { get; set; }
        public virtual Palika Palika { get; set; }
        public virtual State State { get; set; }
        public virtual Sub_Category Sub_Category { get; set; }
    }
}
